apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: proxy
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;
        location / {
          proxy_pass http://wordpress-service.wp.svc.cluster.local:80;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx-proxy
          image: gcr.io/planar-airship-434723-g8/nginx-proxy
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          ports:
            - containerPort: 80
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config



---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: proxy
spec:
    type: LoadBalancer
    selector:
      app: nginx-proxy
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80