apiVersion: v1
kind: Namespace
metadata:
  name: wp
  labels:
    id: c0911181
    app: wordpress
    env: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: db
  labels:
    id: c0911181
    app: mariadb
    env: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: proxy
  labels:
    id: c0911181
    app: nginx-proxy
    env: dev
