apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: db
data:
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wordpress
---
# Database Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        id: c0911181
        app: mariadb
        env: dev
    spec:
      containers:
        - name: mariadb
          image: gcr.io/planar-airship-434723-g8/database
          envFrom:
            - configMapRef:
                name: database-config
            - secretRef:
                name: database-secret
          ports:
            - containerPort: 3306
---
# Database Service
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: db
spec:
  type: NodePort
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
