apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wp
data:
  WORDPRESS_DB_HOST: db
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_NAME: wordpress
---
# WordPress Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        id: c0911181
        app: wordpress
        env: dev
    spec:
      containers:
        - name: wordpress
          image: gcr.io/planar-airship-434723-g8/wordpress
          envFrom:
            - configMapRef:
                name: wordpress-config
            - secretRef:
                name: wordpress-secret
          ports:
            - containerPort: 80
---
# WordPress Service
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wp
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
